version: 2

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test

jobs:
  build:
    docker:
      - image: cimg/base:2021.03
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run: make
      - store_artifacts:
          path: amazon-ecs-agent.tar.gz
  test:
    docker:
      - image: cimg/base:2021.03
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run: make test
